baseURL = "https://monsite-eco.fr/"
languageCode = "fr-fr"
title = "Le Numérique Responsable"

[module]
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"
    version = "v0.0.0-20240227153852-e3e3d066e1ff"

[params]
  custom_css = ["/css/custom.css"]
  favicon = "images/logo.png"
  site_logo = "images/logo.png"
  background = "images/header.jpg"

[params.ananke]
  show_recent_posts = false

[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Impacts du Numérique"
    url = "/impacts/"
    weight = 2
  [[menu.main]]
    name = "Quiz"
    url = "/quiz/"
    weight = 3
  [[menu.main]]
    name = "Stockage"
    url = "/stockage/"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Configuration Netlify Visual Editor
[params.netlify]
  visual_editor = true
  site_id = "numeriqueresponsable"

[params.netlify.collections]
  pages = { path = "content", file = "{slug}.md" }
  articles = { path = "content/articles", file = "{slug}.md" }
  home = { path = "content", file = "_index.md" }