[build]
  publish = "public"
  command = "hugo --minify"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./"

[build.environment]
  HUGO_VERSION = "0.145.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION = "18"
  NETLIFY_USE_YARN = "true"
  NETLIFY_DEV = "true"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "hugo server -D"
  port = 8888
  targetPort = 1313
  publish = "public"
  autoLaunch = true

# Configuration pour Netlify Create
[create]
  enabled = true
  baseDir = "."
  buildCommand = "hugo --minify"
  publishDir = "public"
  allowedRoles = ["admin", "editor"]
  allowedUsers = ["*"]
  configFile = "netlify/create.config.js"

# Configuration Git Gateway
[git]
  gateway = true
  branch = "main"

# Configuration pour l'édition visuelle
[visual-editing]
  enabled = true
  configFile = "netlify/visual-editing.json"