[build]
  command = "hugo mod get -u ./... && hugo --minify"
  publish = "public"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./"

[build.environment]
  HUGO_VERSION = "0.121.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  GO_VERSION = "1.21.0"
  NODE_VERSION = "18"
  NETLIFY_USE_YARN = "true"
  NETLIFY_DEV = "true"
  HUGO_MODULE_REPLACEMENTS = "github.com/theNewDynamic/gohugo-theme-ananke -> github.com/theNewDynamic/gohugo-theme-ananke master"

[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/admin/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "hugo server -D"
  port = 8888
  targetPort = 1313
  publish = "public"
  autoLaunch = true

[dev.environment]
  HUGO_VERSION = "0.121.2"
  HUGO_ENV = "development"
  HUGO_ENABLEGITINFO = "true"
  GO_VERSION = "1.21.0"
  HUGO_MODULE_REPLACEMENTS = "github.com/theNewDynamic/gohugo-theme-ananke -> github.com/theNewDynamic/gohugo-theme-ananke master"

[context.production.environment]
  HUGO_VERSION = "0.121.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  GO_VERSION = "1.21.0"
  HUGO_MODULE_REPLACEMENTS = "github.com/theNewDynamic/gohugo-theme-ananke -> github.com/theNewDynamic/gohugo-theme-ananke master"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.121.2"
  HUGO_ENV = "development"
  HUGO_ENABLEGITINFO = "true"
  GO_VERSION = "1.21.0"
  HUGO_MODULE_REPLACEMENTS = "github.com/theNewDynamic/gohugo-theme-ananke -> github.com/theNewDynamic/gohugo-theme-ananke master"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.121.2"
  HUGO_ENV = "development"
  HUGO_ENABLEGITINFO = "true"
  GO_VERSION = "1.21.0"
  HUGO_MODULE_REPLACEMENTS = "github.com/theNewDynamic/gohugo-theme-ananke -> github.com/theNewDynamic/gohugo-theme-ananke master"

# Configuration pour Netlify Create
[create]
  enabled = true
  baseDir = "."
  buildCommand = "hugo --minify"
  publishDir = "public"
  allowedRoles = ["admin", "editor"]
  allowedUsers = ["*"]
  configFile = "netlify/create.config.js"

# Configuration Git Gateway
[git]
  gateway = true
  branch = "main"

# Configuration pour l'édition visuelle
[visual-editing]
  enabled = true
  configFile = "netlify/visual-editing.json"
  preview = true
  previewUrl = "https://numeriqueresponsable.netlify.app"
  stackbitConfig = "stackbit.config.js"